Game screen
kholkinilya/war_of_ages pull request #4
Opened 2022-03-13 18:09 UTC by FerrumBrain

2022-03-13 18:40 UTC, kholkinilya requested changes

2022-03-13 18:40 UTC, kholkinilya commented on client/src/main.cpp
> +    war_of_ages::client_state state("handle", war_of_ages::screen::GAME_SCREEN);
Начальный экран все-таки скорее стартовое меню, нежели игра. Я так понимаю, ты это добавил пока для дебага, потом главное не забыть убрать.

2022-03-13 18:40 UTC, kholkinilya commented on client/src/game_screen.cpp
> +    auto background = tgui::Picture::create("../client/resources/pictures/background.png");
Там все поле все-равно придется собирать из отдельных спрайтов, которые удобно предоставляет структурка `sprite_supplier`. Иначе никак не обновить эру.

2022-03-13 18:40 UTC, kholkinilya commented on client/src/game_screen.cpp
> +    background->setSize(tgui::String("200%"), tgui::String("150%"));
Мы меряем все в пикселях, поэтому сайз лучше делать абсолютный, подразумевая, что у нас разрешение экрана --- FullHD. Тем не менее, если пользоваться продукцией класса `sprite_supplier`, то тебе не придется думать о размерах, просто надо будет получить и поставить место, где рисовать.

2022-03-13 18:40 UTC, kholkinilya commented on client/src/game_screen.cpp
> +        [&gui]() { show_screen(gui, screen_id.at(screen::SETTINGS), screen_id.at(screen::GAME_SCREEN)); });
Экран настроек в игре должен быть кастомный (?). Ну типа как минимум кнопка "назад" в настройках должна отправлять обратно в игру, а так не получается.

2022-03-13 18:40 UTC, kholkinilya commented on client/src/game_screen.cpp
> +}
Оверол согласен с Антоном, что надо избавится от tgui в этом окошке (кроме кнопок, может(?)).

2022-03-13 18:40 UTC, kholkinilya commented on client/src/wait_screen.cpp
> +}
![image](https://user-images.githubusercontent.com/58657193/158074231-a3e9921c-8478-4c8f-900b-52a862c8d0ac.png)

2022-03-14 00:15 UTC, FerrumBrain commented on client/src/game_screen.cpp
> +}
Думаю, что пока что это не первая необходимость, но да, надо бы

2022-03-18 12:13 UTC, hsevm commented on client/include/ui_functions.h
> +#include "../include/client.h"
```suggestion
#include "screen_defines.h"
```

2022-03-18 12:45 UTC, hsevm commented
Перестало работать турнирное окно с таблицей. При попытке создания программа падает. Не знаю, когда именно сломалось, обнаружил только что

2022-03-18 14:28 UTC, hsevm commented on game_logic/include/game_state.h
> +    [[nodiscard]] game_status get_game_status() const;  // -1 if p1 won, 0 if game is processing, 1 if p2 won
@kholkinilya 
Кажется, комментарий относится к какой-то старой реализации, а сейчас он только вводит в заблуждение
```suggestion
    [[nodiscard]] game_status get_game_status() const;
```

2022-03-18 14:41 UTC, kholkinilya commented on game_logic/include/game_state.h
> +    [[nodiscard]] game_status get_game_status() const;  // -1 if p1 won, 0 if game is processing, 1 if p2 won
да, это верно подмечено

2022-03-18 14:45 UTC, kholkinilya commented on game_logic/include/game_state.h
> +    [[nodiscard]] game_status get_game_status() const;  // -1 if p1 won, 0 if game is processing, 1 if p2 won
Только это скорее в ветку `game_logic_fixes`

2022-03-20 21:42 UTC, closed without merging